import React from "react";
import PageContainer from "../_components/pageContainer";

function Marx() {
  return (
    <PageContainer>
      <p className="text-lg">
        &emsp;&emsp;Karl Marx, in his book Capital, lays out analyses for these
        riots. Mentioning the Luddites specifically, Marx says that laborers and
        what he calls “Machinery” exist in fundamental tension. If a task from a
        worker is automated, the profits that used to be generated by that task
        instead go to the owner of the machine, leaving the worker without a
        means to feed themselves. This situation is obviously undesirable as,
        beyond people starving, it will naturally lead to riots as people feel
        they have no other recourse.
      </p>
    </PageContainer>
  );
}

export default Marx;
