import React from "react";
import PageContainer from "../_components/pageContainer";
import Link from "next/link";

function Marx() {
  return (
    <PageContainer>
      <p className="text-lg">
        &emsp;&emsp;Karl Marx, in his book Capital, lays out analyses for these
        riots. In his apty named &quot;Chapter 15, Section 5: The Strife Between
        Workman and Machine&quot;, Marx says that laborers and what he calls
        “Machinery” exist in fundamental tension{" "}
        <Link className="link" href="/workscited#marx">
          (Marx 287)
        </Link>
        . If a task from a worker is automated, the profits that used to be
        generated by that task instead go to the owner of the machine, leaving
        the worker without a means to feed themselves. This situation is
        obviously undesirable as, beyond people starving, it will naturally lead
        to riots as people feel they have no other recourse.{" "}
      </p>
      <Link className="mt-8" href="/composition">
        <button className="btn btn-secondary">Next Chapter</button>
      </Link>
    </PageContainer>
  );
}

export default Marx;
